### ISSUE TITLE
Python Error during server install

### ISSUE THREAD

**Issue by VertexC** [PiPot/PiPot#10]
ubuntu@ip-172-31-15-79:/usr/src/pipot$ sudo /usr/src/pipot/server/install/install.sh 

Welcome to the PiPot installer!

Detailed information will be written to /usr/src/pipot/server/install/PiPotInstall_2019-02-28_log.txt

-------------------------------
|   Installing dependencies   |
-------------------------------

* Updating package list        
* Installing nginx, python & pip      
* Installing MySQL (root password will be empty!)
* Update setuptools            
* Installing pip dependencies

-------------------------------
|   Configuration of PiPot    |
-------------------------------

In order to configure PiPot, we need some information from you. Please reply to the next questions:

Password of the 'root' user of MySQL: 
Database name for storing data: pipot
Username to connect to pipot: pipot
Password for pipot (will be created): 123456
Server IP: 18.222.168.54
Server interface (SSL): 443
Application root (if not a whole (sub)domain, enter the path. None if whole (sub)domain): None
Instance name: PiPot Command & Control
Path to SSL certificate: /usr/src/pipot/server/cert/pipot.crt
Path to SSL key: /usr/src/pipot/server/cert/pipot.key
Port for SSL Collector to listen on: 1235
Port for UDP Collector to listen on: 1234

We need some information for the admin account
Admin username: admin
Admin email: bob2420083992@gmail.com
Admin password: 123456
Creating admin account: 
Traceback (most recent call last):
  File "/usr/src/pipot/server/install/init_db.py", line 62, in <module>
    run()
  File "/usr/src/pipot/server/install/init_db.py", line 16, in run
    from database import create_session
  File "/usr/src/pipot/server/database.py", line 4, in <module>
    from sqlalchemy import create_engine
ImportError: No module named sqlalchemy

-------------------------------
| Finalizing install of PiPot |
-------------------------------

* Generating secret keys
* Generating config file
* Making necessary scripts executable (if they aren't already)
* Creating startup script
* Creating Nginx config
* Reloading nginx
* Downloading base image

* Starting PiPot...
Starting PiPot daemon...
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/usr/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "/usr/src/pipot/server/bin/pipot.tac", line 4, in <module>
    import config_parser
  File "/usr/src/pipot/server/config_parser.py", line 1, in <module>
    from werkzeug.utils import import_string
exceptions.ImportError: No module named werkzeug.utils

Failed to load application: No module named werkzeug.utils

Traceback (most recent call last):
  File "/usr/src/pipot/server/bin/bootstrap_gunicorn.py", line 16, in <module>
    subprocess.Popen(args)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
PiPot installed!

**Comment by VertexC** [comment]
Ran under AWS ubuntu14.04-amd64
