### ISSUE TITLE
Honeypot mgnt cannot be opened.

### ISSUE THREAD

**Issue by VertexC** [PiPot/PiPot#15]
### Version
latest

### Encountered behaviour
when navigate into honeypot instance/honeypot mgnt, internal error 500 shows.

### Additional information
In error.log
Traceback (most recent call last):
  File "/usr/src/pipot/pipot-env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/src/pipot/pipot-env/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/src/pipot/pipot-env/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/src/pipot/pipot-env/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/src/pipot/pipot-env/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/pipot/server/mod_auth/controllers.py", line 48, in decorated_function
    return f(*args, **kwargs)
  File "/usr/src/pipot/server/mod_auth/controllers.py", line 71, in decorated_function
    return f(*args, **kwargs)
  File "/usr/src/pipot/server/decorators.py", line 63, in decorated_function
    result = {
  File "/usr/src/pipot/server/mod_honeypot/controllers.py", line 178, in manage
    addrs = ni.ifaddresses('eth0')
ValueError: You must specify a valid interface name.

**Comment by VertexC** [comment]
The eth0 is hardcoded but may now always the case, we may want to allow user to specify which network interface they want to use for instance deployment.
