### ISSUE TITLE
500 Internal Server Error after logging into the web app as admin

### ISSUE THREAD

**Issue by bangpradyumna** [PiPot/PiPot#9]
### Expected behavior
The app should log the admin in properly and display the dashboard.

### Encountered behavior
500 Internal server error was received and when the error.log file was retrieved, It showed the following error :
`Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/pipot/server/mod_auth/controllers.py", line 48, in decorated_function
    return f(*args, **kwargs)
  File "/usr/src/pipot/server/mod_auth/controllers.py", line 71, in decorated_function
    return f(*args, **kwargs)
  File "/usr/src/pipot/server/decorators.py", line 63, in decorated_function
    ctx = f(*args, **kwargs)
  File "/usr/src/pipot/server/mod_report/controllers.py", line 54, in dashboard
    'form': DashboardForm()
  File "/usr/local/lib/python2.7/dist-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/usr/src/pipot/server/mod_report/forms.py", line 23, in __init__
    csrf_enabled, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_wtf/form.py", line 158, in __init__
    super(Form, self).__init__(*args, **kwargs)
TypeError: __init__() takes at most 2 arguments (7 given)` 

The complete error.log can be found at : https://gist.github.com/theweblover007/d783e06d8698fa0b9d40d6a1611b0b0f

### Additional information

Error occurs when __init__ of DashboardForm is called with self and 6 other arguments, This leads to the super function of this form class i.e Form class in ..../dist-packages/flask_wtf/form.py to be called.  (This class will be depreciated in the further releases). Now, the parent class of this Form class named FlaskForm in the same file is called which ultimately leads to a call to 'Form' class in ...../dist-packages/wtforms/form.py from where I could not make out what was happening.

Is the same name 'Form' of two classes causing the issue? Or something entirely different is happening? Please help me solve this issue by providing the correct direction.

**Comment by bangpradyumna** [comment]
Issue fixed.
